package tw.com.seesawin.ex06;

import java.net.*;

public class Exception0 {
	public static void main(String[] args) {
/*
		// pay no attention to unchecked exception
		int i = Integer.parseInt(args[0]);

		// unchecked exception can also be caught
		int j = 0;
		try {
			j = Integer.parseInt(args[0]);
		} catch (NumberFormatException nfe) {
			System.out.println(nfe.getMessage());
			nfe.printStackTrace();
		}

		// checked exception must be handled
		try {
			URL u = new URL(args[0]);
		} catch (MalformedURLException mfe) {
			System.out.println(mfe.getMessage());
			mfe.printStackTrace();
		}

		// after the exception has been caught,
		// it's like the exception never happend
		System.out.println("normal process resume here");

		// ArithmeticException is a subclass of Exception
		try {
			if (args[0].equals("1")) {
				throw new ArithmeticException();
			} else {
				throw new Exception();
			}
		} catch (Exception e) {
			System.out.println("Exception");
		} catch (ArithmeticException ae) {
			System.out.println("ArithmeticException");
		}

		// finally always happend
		try {
			// throw new Exception();
			// throw new InternalError();
			// return;
			// System.exit(1);
		} catch (Exception e) {
			System.out.print("A");
		} finally {
			System.out.print("B");
		}
		System.out.print("C");

		try {
			System.out.print("D");
		} finally {
			System.out.print("E");
		}
*/
	}
}
